[package]
name = "common"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
wasefire-wire = { path = "../../../../crates/wire" }

[dependencies.serde]
version = "1.0.229"
default-features = false
features = ["alloc", "derive"]
optional = true

[features]
serde = ["dep:serde"]

[lints]
clippy.mod_module_files = "warn"
clippy.unit_arg = "allow"
rust.unreachable_pub = "warn"
rust.unused_crate_dependencies = "warn"
