[package]
name = "wasefire-logger"
version = "0.2.2-git"
edition = "2024"
description = "Wasefire platform logging"
repository = "https://github.com/google/wasefire"
license = "Apache-2.0"
keywords = ["embedded", "framework", "no-std", "wasm"]
categories = ["embedded", "no-std", "wasm"]
include = ["/LICENSE", "/src/"]
publish = true

[dependencies]
defmt = { version = "1.1.0", default-features = false, optional = true }
log = { version = "0.4.33", default-features = false, optional = true }

[features]
defmt = ["dep:defmt"]
log = ["dep:log"]

[lints]
clippy.mod-module-files = "warn"
clippy.uninlined_format_args = "allow"
clippy.unit-arg = "allow"
rust.unreachable-pub = "warn"
rust.unused-crate-dependencies = "warn"
