[package]
name = "part-4-sol"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
interface = { path = "../interface" }
wasefire = { path = "../../../../crates/prelude" }

[lints]
clippy.mod_module_files = "warn"
clippy.unit_arg = "allow"
rust.unused_crate_dependencies = "warn"
