comment_width = 100
fn_params_layout = "Compressed"
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
spaces_around_ranges = true
use_small_heuristics = "Max"
where_single_line = true
wrap_comments = true
