[files]
# Exclude .gitignore and submodules.
exclude = [".root/**", "target/**", "third_party/**"]

[format.rules]
line-width = 100

[[schemas]]
path = "target/tombi/https/www.schemastore.org/cargo.json"
include = ["Cargo.toml"]
