[package]
name = "gcm_test"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
aead = { version = "0.5.2", default-features = false, features = ["alloc"], optional = true }
wasefire = { path = "../../../crates/prelude" }

[features]
rust-crypto = ["dep:aead", "wasefire/rust-crypto"]

[lints]
clippy.mod_module_files = "warn"
clippy.unit_arg = "allow"
rust.unreachable_pub = "warn"
rust.unused_crate_dependencies = "warn"
