[package]
name = "threads"
version = "0.1.0"
authors = ["Dan Kluser <kluserdb@google.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
wasefire = { path = "../../../crates/prelude" }

[features]
threads = []
