[package]
name = "wasefire-cli"
version = "0.4.1-git"
edition = "2024"
description = "Wasefire CLI to manage applets and platforms"
repository = "https://github.com/google/wasefire"
license = "Apache-2.0"
keywords = ["cli", "embedded", "framework", "wasm"]
categories = ["command-line-utilities", "embedded", "wasm"]
include = ["/LICENSE", "/src/"]
publish = true

[[bin]]
name = "wasefire"
path = "src/main.rs"

[dependencies]
anyhow = { version = "1.0.104", default-features = false }
clap = { version = "4.6.5", default-features = false, features = ["default", "derive", "env"] }
clap_complete = { version = "4.6.8", default-features = false }
env_logger = { version = "0.11.11", default-features = false, features = ["default"] }
target-triple = { version = "1.0.1", default-features = false }
wasefire-cli-tools = { path = "../cli-tools", version = "0.4.1-git", features = ["action"] }
wasefire-one-of = { path = "../one-of", version = "0.1.3-git" }

[dependencies.tokio]
version = "1.53.1"
default-features = false
features = ["macros", "parking_lot", "rt", "rt-multi-thread"]

[features]
_dev = []
_prod = []

[lints]
clippy.mod_module_files = "warn"
clippy.uninlined_format_args = "allow"
clippy.unit_arg = "allow"
rust.unreachable_pub = "warn"
rust.unused_crate_dependencies = "warn"
