[package]
name = "host"
version = "0.1.0"
authors = ["Julien Cretin <cretin@google.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.1.14", features = ["derive"] }
common = { path = "../common", features = ["std"] }
env_logger = "0.10.0"
log = "0.4.17"
serialport = "4.2.0"
