[package]
name = "host"
version = "0.1.0"
authors = ["Julien Cretin <cretin@google.com>"]
license = "Apache-2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.46", features = ["derive"] }
common = { path = "../common", features = ["std"] }
env_logger = "0.11.8"
log = "0.4.27"
wasefire-cli-tools = { path = "../../../../crates/cli-tools", features = ["action"] }

[lints]
clippy.literal-string-with-formatting-args = "allow"
clippy.mod-module-files = "warn"
clippy.unit-arg = "allow"
rust.unreachable-pub = "warn"
rust.unused-crate-dependencies = "warn"
