[package]
name = "host"
version = "0.1.0"
authors = ["Julien Cretin <cretin@google.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.4", features = ["derive"] }
common = { path = "../common", features = ["std"] }
env_logger = "0.11.3"
log = "0.4.21"
serialport = "4.3.0"
