[package]
name = "ecdh_test"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
ecdh_vectors = { path = "../ec_test/crates/ecdh_vectors" }
wasefire = { path = "../../../crates/prelude" }
wasefire-one-of = { path = "../../../crates/one-of" }
wasefire-stub = { path = "../../../crates/stub", optional = true }

[features]
runner- = []
runner-opentitan = []
test = ["dep:wasefire-stub", "wasefire/test"]

[lints]
clippy.mod_module_files = "warn"
clippy.unit_arg = "allow"
rust.unreachable_pub = "warn"
rust.unused_crate_dependencies = "warn"
