[package]
name = "wasefire-slice-cell"
version = "0.1.2-git"
edition = "2024"
description = "Slice with dynamic borrow checking"
repository = "https://github.com/google/wasefire"
license = "Apache-2.0"
keywords = ["borrow", "cell", "lifetime", "no-std", "slice"]
categories = ["data-structures", "memory-management", "no-std"]
include = ["/LICENSE", "/src/"]
publish = true

[features]
_internal = []

[lints]
clippy.mod_module_files = "warn"
clippy.uninlined_format_args = "allow"
clippy.unit_arg = "allow"
rust.unreachable_pub = "warn"
rust.unused_crate_dependencies = "warn"
