[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.5", features = ["derive"] }
data-encoding = "2.11.1"
env_logger = "0.11.11"
libc = "0.2.189"
log = "0.4.33"
object = "0.40.0"
serde = { version = "1.0.229", features = ["derive"] }
serialport = "4.9.0"
tokio = { version = "1.53.1", features = ["full"] }
wasefire-cli-tools = { path = "../cli-tools", features = ["action", "changelog"] }
wasefire-error = { path = "../error", features = ["std"] }
wasefire-protocol = { path = "../protocol", features = ["host"] }

[lints]
clippy.mod_module_files = "warn"
clippy.uninlined_format_args = "allow"
clippy.unit_arg = "allow"
rust.unreachable_pub = "warn"
rust.unused_crate_dependencies = "warn"
