[package]
name = "part-3-sol"
version = "0.1.0"
authors = ["Julien Cretin <cretin@google.com>"]
license = "Apache-2.0"
edition = "2024"

[dependencies]
interface = { path = "../interface" }
wasefire = { path = "../../../../crates/prelude" }

[lints]
clippy.mod-module-files = "warn"
clippy.unit-arg = "allow"
rust.unused-crate-dependencies = "warn"
