[alias]
update-api = "run --manifest-path ./crates/api-desc/crates/update/Cargo.toml"
wasefire = "run --manifest-path ./crates/cli/Cargo.toml --"
xtask = "run --manifest-path ./crates/xtask/Cargo.toml --"

[build]
target-dir = "target"
