inputs:
  check:
    required: true
  token:
    required: true

runs:
  using: composite
  steps:
    - if: ${{ contains(fromJSON('["changelog", "copyright", "sync"]'), inputs.check) }}
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        fetch-depth: 0
    - name: Restore the cache
      uses: ./.github/actions/ci-cache
    - run: sudo apt-get update
      shell: bash
    - run: ./scripts/setup.sh
      shell: bash
    - if: ${{ inputs.check == 'copyright' }}
      run: ./scripts/ci-copyright.sh
      shell: bash
    - if: ${{ inputs.check == 'changelog' }}
      run: ./scripts/ci-changelog.sh
      shell: bash
    - if: ${{ inputs.check == 'textreview' }}
      run: cargo xtask textreview
      shell: bash
    - if: ${{ inputs.check == 'sync' }}
      run: ./scripts/sync.sh
      shell: bash
    - if: ${{ inputs.check == 'publish' }}
      run: ./scripts/publish.sh --dry-run
      shell: bash
    - if: ${{ inputs.check == 'markdown' }}
      run: ./scripts/wrapper.sh mdl -g -s markdownlint.rb .
      shell: bash
    - if: ${{ inputs.check == 'taplo' }}
      run: ./scripts/ci-taplo.sh
      shell: bash
    - if: ${{ inputs.check == 'applets' }}
      run: ./scripts/ci-applets.sh
      shell: bash
    - if: ${{ inputs.check == 'runners' }}
      run: ./scripts/ci-runners.sh
      shell: bash
    - if: ${{ startsWith(inputs.check, 'tests-') }}
      run: ./scripts/ci-tests.sh $(sed s/tests-// <<< ${{ inputs.check }}) 8
      shell: bash
    - if: ${{ inputs.check == 'hw-host' }}
      run: ./scripts/hwci.sh host
      shell: bash
    - if: ${{ inputs.check == 'book' }}
      run: ./scripts/ci-book.sh
      shell: bash
    - if: ${{ inputs.check == 'footprint' }}
      name: Compute footprint
      uses: ./.github/actions/ci-footprint
      with:
        token: ${{ inputs.token }}
    - run: git diff --exit-code
      shell: bash
    - run: '[ -z "$(git status -s | tee /dev/stderr)" ]'
      shell: bash
