inputs:
  checks:
    required: true
  token:
    required: true
  use-cache:
    default: 'true'

runs:
  using: composite
  steps:
    - if: >-
        ${{ contains(fromJSON(inputs.checks), 'changelog')
         || contains(fromJSON(inputs.checks), 'copyright')
         || contains(fromJSON(inputs.checks), 'sync') }}
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0
    - if: inputs.use-cache == 'true'
      name: Restore the cache
      uses: ./.github/actions/ci-cache
    - run: sudo apt-get update
      shell: bash
    - run: ./scripts/setup.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'copyright') }}
      run: ./scripts/ci-copyright.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'changelog') }}
      run: ./scripts/ci-changelog.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'textreview') }}
      run: cargo xtask textreview
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'sync') }}
      run: ./scripts/sync.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'publish') }}
      run: ./scripts/publish.sh --dry-run
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'markdown') }}
      run: ./scripts/wrapper.sh mdl -g -s markdownlint.rb .
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'taplo') }}
      run: ./scripts/ci-taplo.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'applets') }}
      run: ./scripts/ci-applets.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'runners') }}
      run: ./scripts/ci-runners.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'tests-0') }}
      run: ./scripts/ci-tests.sh 0 8
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'tests-1') }}
      run: ./scripts/ci-tests.sh 1 8
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'tests-2') }}
      run: ./scripts/ci-tests.sh 2 8
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'tests-3') }}
      run: ./scripts/ci-tests.sh 3 8
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'tests-4') }}
      run: ./scripts/ci-tests.sh 4 8
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'tests-5') }}
      run: ./scripts/ci-tests.sh 5 8
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'tests-6') }}
      run: ./scripts/ci-tests.sh 6 8
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'tests-7') }}
      run: ./scripts/ci-tests.sh 7 8
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'hw-host') }}
      run: ./scripts/hwci.sh host
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'book') }}
      run: ./scripts/ci-book.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'footprint') }}
      name: Compute footprint
      uses: ./.github/actions/ci-footprint
      with:
        upload: ${{ toJSON(inputs.use-cache == 'true') }}
        token: ${{ inputs.token }}
    - run: git diff --exit-code
      shell: bash
    - run: '[ -z "$(git status -s | tee /dev/stderr)" ]'
      shell: bash
