inputs:
  checks:
    required: true
  token:
    required: true
  use-cache:
    default: 'true'

runs:
  using: composite
  steps:
    - if: ${{ contains(fromJSON(inputs.checks), 'changelog') }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - if: inputs.use-cache == 'true'
      name: Restore the cache
      uses: ./.github/actions/ci-cache
    # TODO(https://github.com/microsoft/linux-package-repositories/issues/130): Remove when fixed.
    - run: sudo rm /etc/apt/sources.list.d/microsoft-prod.list
      shell: bash
    - run: sudo apt-get update
      shell: bash
    - run: ./scripts/setup.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'copyright') }}
      run: ./scripts/ci-copyright.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'changelog') }}
      run: ./scripts/ci-changelog.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'textreview') }}
      run: cargo xtask textreview
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'sync') }}
      run: ./scripts/sync.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'publish') }}
      run: ./scripts/publish.sh --dry-run
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'markdown') }}
      # TODO: Keep only the last command once ubuntu-latest is 24.04.
      run: |
        set -x
        curl -Os http://ftp.de.debian.org/debian/pool/main/r/ruby-mdl/markdownlint_0.13.0-4_all.deb
        sudo apt install ruby-kramdown-parser-gfm ruby-mixlib-{cli,config,shellout}
        sudo dpkg -i markdownlint_0.13.0-4_all.deb
        rm markdownlint_0.13.0-4_all.deb
        ./scripts/wrapper.sh mdl -g -s markdownlint.rb .
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'taplo') }}
      run: ./scripts/ci-taplo.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'applets') }}
      run: ./scripts/ci-applets.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'runners') }}
      run: ./scripts/ci-runners.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'tests-0') }}
      run: ./scripts/ci-tests.sh 0 3
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'tests-1') }}
      run: ./scripts/ci-tests.sh 1 3
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'tests-2') }}
      run: ./scripts/ci-tests.sh 2 3
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'hw-host') }}
      run: ./scripts/hwci.sh host --no-default-features
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'book') }}
      run: ./scripts/ci-book.sh
      shell: bash
    - if: ${{ contains(fromJSON(inputs.checks), 'footprint') }}
      name: Compute footprint
      uses: ./.github/actions/ci-footprint
      with:
        upload: ${{ toJSON(inputs.use-cache == 'true') }}
        token: ${{ inputs.token }}
    - run: git diff --exit-code
      shell: bash
    - run: '[ -z "$(git status -s | tee /dev/stderr)" ]'
      shell: bash
