[package]
name = "common"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
thiserror = { version = "2.0.19", optional = true }

[features]
std = ["dep:thiserror"]

[lints]
clippy.mod_module_files = "warn"
clippy.unit_arg = "allow"
rust.unreachable_pub = "warn"
rust.unused_crate_dependencies = "warn"
