[package]
name = "opentitan"
version = "0.1.0"
authors = ["Julien Cretin <cretin@google.com>"]
license = "Apache-2.0"
edition = "2024"

[dependencies]
ecdh_vectors = { path = "../ecdh_vectors" }
elliptic-curve = { version = "0.13.8", features = ["sec1"] }
p256 = "0.13.2"
p384 = "0.13.1"

[lints]
clippy.mod-module-files = "warn"
clippy.unit-arg = "allow"
rust.unreachable-pub = "warn"
rust.unused-crate-dependencies = "warn"
