[package]
name = "opentitan"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
ecdh_vectors = { path = "../ecdh_vectors" }
elliptic-curve = { version = "0.13.8", features = ["sec1"] }
p256 = "0.13.2"
p384 = "0.13.1"

[lints]
clippy.mod_module_files = "warn"
clippy.unit_arg = "allow"
rust.unreachable_pub = "warn"
rust.unused_crate_dependencies = "warn"
