inputs:
  token:
    required: true

runs:
  using: composite
  steps:
    - run: ./scripts/footprint.sh
      shell: bash
    - run: mv footprint.toml footprint-${{ github.event_name }}.toml
      shell: bash
    - if: github.event_name == 'push'
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: footprint
        path: footprint-push.toml
    - if: github.event_name == 'pull_request'
      id: main-run
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const { data } = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'ci.yml',
            branch: 'main',
            event: 'push',
            head_sha: '${{ github.event.pull_request.base.sha }}',
          });
          return data.workflow_runs[0]?.id ?? 0;
    - if: github.event_name == 'pull_request'
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        name: footprint
        github-token: ${{ inputs.token }}
        run-id: ${{ steps.main-run.outputs.result }}
      continue-on-error: true
    - if: github.event_name == 'pull_request'
      run: cargo xtask footprint "$GITHUB_STEP_SUMMARY"
      shell: bash
    - run: rm footprint-*.toml
      shell: bash
