inputs:
  upload:
    required: true
  token:
    required: true

runs:
  using: composite
  steps:
    - run: ./scripts/footprint.sh
      shell: bash
    - run: mv footprint.toml footprint-${{ github.event_name }}.toml
      shell: bash
    - if: github.event_name == 'push' && inputs.upload == 'true'
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: footprint
        path: footprint-push.toml
    - if: github.event_name == 'pull_request'
      id: main-run
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const { data } = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'ci.yml',
            branch: 'main',
            event: 'push',
            head_sha: '${{ github.event.pull_request.base.sha }}',
          });
          return data.workflow_runs[0]?.id ?? 0;
    - if: github.event_name == 'pull_request'
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: footprint
        github-token: ${{ inputs.token }}
        run-id: ${{ steps.main-run.outputs.result }}
      continue-on-error: true
    - if: github.event_name == 'pull_request'
      run: cargo xtask footprint "$GITHUB_STEP_SUMMARY"
      shell: bash
    - run: rm footprint-*.toml
      shell: bash
