[package]
name = "syscall-test"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
defmt = { version = "1.1.0", default-features = false, optional = true }
wasefire-board-api = { path = "../..", features = ["api-vendor"] }

[features]
defmt = ["dep:defmt"]

[lints]
clippy.mod-module-files = "warn"
clippy.uninlined_format_args = "allow"
clippy.unit-arg = "allow"
rust.unreachable-pub = "warn"
rust.unused-crate-dependencies = "warn"
