[package]
name = "wasefire-cli-tools"
version = "0.1.0-git"
authors = ["Julien Cretin <cretin@google.com>"]
license = "Apache-2.0"
publish = true
edition = "2021"
description = "Command-line utilities for Wasefire"
repository = "https://github.com/google/wasefire"
include = ["/src"]
keywords = ["cli", "embedded", "framework", "wasm"]
categories = ["command-line-utilities", "embedded", "wasm"]

[dependencies]
anyhow = { version = "1.0.86", default-features = false, features = ["std"] }
cargo_metadata = { version = "0.18.1", default-features = false }
clap = { version = "4.5.4", default-features = false, features = ["derive", "std"] }
serde = { version = "1.0.202", default-features = false, features = ["derive"] }
toml = { version = "0.8.13", default-features = false, features = ["display", "parse"] }

[lints]
clippy.unit-arg = "allow"
rust.unreachable-pub = "warn"
rust.unsafe-op-in-unsafe-fn = "warn"
rust.unused-crate-dependencies = "warn"
