[package]
name = "wasefire-store"
version = "0.3.3-git"
edition = "2024"
description = "Key-value store for SLC flash storage"
repository = "https://github.com/google/wasefire"
license = "Apache-2.0"
keywords = ["embedded", "no-std"]
categories = ["embedded", "no-std"]
include = ["/LICENSE", "/src/"]
publish = true

[package.metadata.docs.rs]
features = ["std"]

[dependencies]
wasefire-error = { path = "../error", version = "0.1.5-git" }

[dev-dependencies]
tempfile = "3.27.0"

[features]
std = ["wasefire-error/std"]

[lints]
clippy.mod_module_files = "warn"
clippy.uninlined_format_args = "allow"
clippy.unit_arg = "allow"
rust.unreachable_pub = "warn"
rust.unused_crate_dependencies = "warn"
