[package]
name = "part-5"
version = "0.1.0"
authors = ["Julien Cretin <cretin@google.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
interface = { path = "../interface" }
wasefire = { path = "../../../../crates/prelude" }
