[package]
name = "fuzz"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[package.metadata]
cargo-fuzz = true

[[bin]]
name = "store"
path = "fuzz_targets/store.rs"

[dependencies]
libfuzzer-sys = "0.4.12"
rand_pcg = "0.10.2"
strum = { version = "0.28.0", features = ["derive"] }
wasefire-store = { path = "..", features = ["std"] }

[lints]
clippy.mod-module-files = "warn"
clippy.uninlined_format_args = "allow"
clippy.unit-arg = "allow"
