inputs:
  mode:
    default: restore

outputs:
  cache-hit:
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    # It would be nice to factorize path and key.
    - if: inputs.mode == 'restore'
      uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          .root/
          target/
        key: ${{ hashFiles('rust-toolchain.toml', 'scripts/wrapper.sh') }}
    - if: inputs.mode == 'save'
      id: cache
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          .root/
          target/
        key: ${{ hashFiles('rust-toolchain.toml', 'scripts/wrapper.sh') }}
