inputs:
  mode:
    default: restore

outputs:
  cache-hit:
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    # It would be nice to factorize path and key.
    - if: inputs.mode == 'restore'
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          .root/
          target/
        key: ${{ hashFiles('rust-toolchain.toml', 'scripts/wrapper.sh') }}
    - if: inputs.mode == 'save'
      id: cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          .root/
          target/
        key: ${{ hashFiles('rust-toolchain.toml', 'scripts/wrapper.sh') }}
