inputs:
  mode:
    default: restore

outputs:
  cache-hit:
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    # It would be nice to factorize path and key.
    - if: inputs.mode == 'restore'
      uses: actions/cache/restore@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          .root/
          target/
        key: ${{ hashFiles('rust-toolchain.toml', 'scripts/wrapper.sh') }}
    - if: inputs.mode == 'save'
      id: cache
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          .root/
          target/
        key: ${{ hashFiles('rust-toolchain.toml', 'scripts/wrapper.sh') }}
