inputs:
  mode:
    default: restore

outputs:
  cache-hit:
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    # It would be nice to factorize path and key.
    - if: inputs.mode == 'restore'
      uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          .root/
          target/
        key: ${{ hashFiles('rust-toolchain.toml', 'scripts/wrapper.sh') }}
    - if: inputs.mode == 'save'
      id: cache
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          .root/
          target/
        key: ${{ hashFiles('rust-toolchain.toml', 'scripts/wrapper.sh') }}
