[book]
authors = ["Julien Cretin <cretin@google.com>"]
language = "en"
src = "src"
title = "Wasefire"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/google/wasefire/tree/main/book"
