[package]
name = "host"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.103"
clap = { version = "4.6.1", features = ["derive"] }
common = { path = "../common" }
data-encoding = "2.11.0"
signal-hook = "0.4.4"
tokio = { version = "1.52.3", features = ["full"] }
wasefire-cli-tools = { path = "../../../../crates/cli-tools", features = ["action"] }
wasefire-error = { path = "../../../../crates/error" }
wasefire-protocol = { path = "../../../../crates/protocol", features = ["host"] }
wasefire-wire = { path = "../../../../crates/wire" }

[lints]
clippy.mod-module-files = "warn"
clippy.unit-arg = "allow"
rust.unreachable-pub = "warn"
rust.unused-crate-dependencies = "warn"
