[package]
name = "fingerprint"
version = "0.1.0"
authors = ["Julien Cretin <cretin@google.com>"]
license = "Apache-2.0"
edition = "2024"

[dependencies]
common = { path = "common" }
wasefire = { path = "../../../crates/prelude" }
wasefire-wire = { path = "../../../crates/wire" }

[lints]
clippy.mod-module-files = "warn"
clippy.unit-arg = "allow"
rust.unreachable-pub = "warn"
rust.unused-crate-dependencies = "warn"
